name: Vulnerability Check

on:
  schedule:
    - cron: '0 3 * * *'

env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/primary-nginx

jobs:
  schedule-scan:
    runs-on: ubuntu-18.04
    steps:
    - name: Get Information Of Latest Version
      run: |
        PKG_VERSION="$(curl -s "https://api.github.com/repos/chiguhagu/primary-nginx/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -d 'v' -f 2)"
        echo "::set-env name=TARGET_PKG::${DOCKER_BASE_NAME}:${PKG_VERSION}"

    - name: Login Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u chiguhagu --password-stdin

    - name: Pull Image
      run: |
        docker pull ${TARGET_PKG}

    - name: Cached Scan Db
      uses: actions/cache@preview
      with:
        path: vulndb/
        key: trivy-vulndb

    - name: Install Trivy
      run: |
        trivyRelease="$(curl -s "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -d 'v' -f 2)"
        wget https://github.com/aquasecurity/trivy/releases/download/v${trivyRelease}/trivy_${trivyRelease}_Linux-64bit.tar.gz
        tar zxvf trivy_${trivyRelease}_Linux-64bit.tar.gz

    - name: Scan Image
      run: ./trivy --exit-code 1 --no-progress --severity CRITICAL --cache-dir vulndb/ "${TARGET_PKG}"
